# The URL the site will be built for
base_url = "https://williamyoon2021.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "~/williamyoon2021"


description = "William's personal website."

theme = "tabi"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "kronuz"
smart_punctuation = true

[extra]
# Put all your custom variables here
#Makes site green
skin = "mint"
browser_theme_color = ["#00b86e", "#00804d"]
favicon = "favicon.ico"


#Nav Menu
menu = [
    { name = "About me", url = "about", trailing_slash = true },
    { name = "Research", url = "research", trailing_slash = true},
    { name = "Projects", url = "projects", trailing_slash = true },
    { name = "Resume", url = "resume", trailing_slash = true },
    
]

#base64 encoded email used in footer
email = "wty5@cornell.edu"

#Footer socials
socials = [
    { name = "github", url = "https://github.com/williamyoon2021/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/william-yoon/", icon = "linkedin" },
]


allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
    { directive = "frame-src", domains = ["'self'", "player.vimeo.com", "https://www.youtube-nocookie.com"] },
]

show_reading_time = false